#!/bin/sh
set -eu

# JSON TO TABLE

# Shell wrapper for json2load.py, json2rate.py, json2loss.py

usage()
{
  echo "Usage: <mode> <root_dir> <output_file>"
}

if [ ${#*} = 0 ]
then
  usage
  exit 1
fi
MODE=$1
shift

THIS=$( dirname $0 )
export PYTHONPATH=$THIS:${PYTHONPATH:-}

PROGRAM=$THIS/json2$MODE.py
if ! [ -e $PROGRAM ]
then
  echo "No such mode: $MODE"
  usage
  exit 1
fi

python $PROGRAM $*
